# Generated by Django 3.1.4 on 2020-12-31 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('year', models.IntegerField()),
                ('genre', models.CharField(choices=[('RR', 'Rock'), ('FS', 'Funk / Soul'), ('JZ', 'Jazz'), ('LB', 'Blues'), ('PP', 'Pop'), ('FK', 'Folk'), ('CL', 'Classical'), ('RG', 'Reggae'), ('HH', 'Hip Hop'), ('EL', 'Electronic'), ('LT', 'Latin')], default='RR', max_length=2)),
                ('primary_artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.artist')),
            ],
        ),
    ]
