# Generated by Django 3.1.4 on 2021-01-04 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20210103_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='image',
            field=models.ImageField(default='music_genres/default.jpg', upload_to='music_genres'),
        ),
    ]
